/* 
 * CX - C++ framework for general purpose development
 *
 * https://github.com/draede/cx
 * 
 * Copyright (C) 2014 - 2021 draede - draede [at] outlook [dot] com
 *
 * Released under the MIT License.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */ 

#pragma once


#include <bitset>
#include <cstddef>
#include <ctype.h>
#include <deque>
#include <errno.h>
#include <functional>
#include <limits.h>
#include <limits>
#include <list>
#include <map>
#include <new>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <stdarg.h>
#include <stddef.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <wchar.h>
#include <wchar.h>
#include <wctype.h>

#include "LZ4.h"
#include "aes.h"
#include "bson.h"
#include "bson.h"
#include "byteorder.h"
#include "curl/curl.h"
#include "document.h"
#include "expat.h"
#include "lz4.h"
#include "lz4hc.h"
#include "lzham.h"
#include "memorystream.h"
#include "rapidjson.h"
#include "rapidjson.h"
#include "reader.h"
#include "snappy.h"
#include "sparsehash/dense_hash_map"
#include "sparsehash/dense_hash_set"
#include "sparsehash/internal/sparseconfig.h"
#include "sparsehash/sparse_hash_map"
#include "sparsehash/sparse_hash_set"
#include "sqlite3.h"
#include "stringbuffer.h"
#include "writer.h"
#include "xxhash.h"

#include "CX/APIDefs.hpp"
#include "CX/Archive/LZ4InputFilter.hpp"
#include "CX/Archive/LZ4OutputFilter.hpp"
#include "CX/Archive/LZHAMInputFilter.hpp"
#include "CX/Archive/LZHAMOutputFilter.hpp"
#include "CX/Archive/SnappyInputFilter.hpp"
#include "CX/Archive/SnappyOutputFilter.hpp"
#include "CX/BLOB.hpp"
#include "CX/BitSet.hpp"
#include "CX/C/APIDefs.h"
#include "CX/C/Limits.h"
#include "CX/C/Mem.h"
#include "CX/C/Platform.h"
#include "CX/C/Platform/Windows/Types.h"
#include "CX/C/Platform/Windows/ctype.h"
#include "CX/C/Platform/Windows/stdarg.h"
#include "CX/C/Platform/Windows/stdio.h"
#include "CX/C/Platform/Windows/stdlib.h"
#include "CX/C/Platform/Windows/string.h"
#include "CX/C/Platform/Windows/windows.h"
#include "CX/C/Scope.h"
#include "CX/C/StatusCodes.h"
#include "CX/C/Types.h"
#include "CX/C/Version.h"
#include "CX/C/ctype.h"
#include "CX/C/stdarg.h"
#include "CX/C/stdio.h"
#include "CX/C/stdlib.h"
#include "CX/C/string.h"
#include "CX/CBuffers/Buffer.h"
#include "CX/CBuffers/CLibEnvironment.h"
#include "CX/CBuffers/Environment.h"
#include "CX/CBuffers/Struct.h"
#include "CX/CBuffers/Tools/CPP_Generator.hpp"
#include "CX/CBuffers/Tools/C_Generator.hpp"
#include "CX/CBuffers/Tools/IGenerator.hpp"
#include "CX/CBuffers/Tools/IMemoryStream.hpp"
#include "CX/CBuffers/Tools/IStream.hpp"
#include "CX/CBuffers/Tools/InputStreamStream.hpp"
#include "CX/CBuffers/Tools/Parser.hpp"
#include "CX/CBuffers/Tools/ParserData.hpp"
#include "CX/CBuffers/Types.h"
#include "CX/CLI/CmdLine.hpp"
#include "CX/CLI/ICommand.hpp"
#include "CX/CLI/Commands.hpp"
#include "CX/Crypt/AES128InputFilter.hpp"
#include "CX/Crypt/AES128OutputFilter.hpp"
#include "CX/DB/Flat/Reader.hpp"
#include "CX/DB/Flat/Writer.hpp"
#include "CX/DB/Flat/Reader.hpp"
#include "CX/DB/Flat/Writer.hpp"
#include "CX/DB/SQLite/Bindings.hpp"
#include "CX/DB/SQLite/DBHelper.hpp"
#include "CX/DB/SQLite/Database.hpp"
#include "CX/DB/SQLite/DefaultDBHelperAsyncMgr.hpp"
#include "CX/DB/SQLite/IDBHelperAsyncMgr.hpp"
#include "CX/DB/SQLite/Statement.hpp"
#include "CX/DB/SQLite/Transaction.hpp"
#include "CX/Data/JSON/DumpSAXParserObserver.hpp"
#include "CX/Data/JSON/ISAXParserObserver.hpp"
#include "CX/Data/JSON/Node.hpp"
#include "CX/Data/JSON/RapidJSONStreams.hpp"
#include "CX/Data/JSON/SAXParser.hpp"
#include "CX/Data/MO/ISAXParserObserver.hpp"
#include "CX/Data/MO/Language.hpp"
#include "CX/Data/MO/SAXParser.hpp"
#include "CX/Data/XML/ISAXParserObserver.hpp"
#include "CX/Data/XML/Node.hpp"
#include "CX/Data/XML/SAXParser.hpp"
#include "CX/Data/XML/SAXParserObserverBase.hpp"
#include "CX/Debug/IProfilingHandler.hpp"
#include "CX/Debug/PrintProfilingHandler.hpp"
#include "CX/Debug/Profiler.hpp"
#include "CX/Debug/ScopeProfiler.hpp"
#include "CX/Debug/SysLogProfilingHandler.hpp"
#include "CX/Debug/ThreadProfiler.hpp"
#include "CX/DenseHashMap.hpp"
#include "CX/DenseMultiHashSet.hpp"
#include "CX/Deque.hpp"
#include "CX/Detail/DetailPrint/DetailPrint.hpp"
#include "CX/EmptyType.hpp"
#include "CX/GSHAlloc.hpp"
#include "CX/Hash/BLAKE2Hash.hpp"
#include "CX/Hash/CRC32Hash.hpp"
#include "CX/Hash/IHash.hpp"
#include "CX/Hash/MD5Hash.hpp"
#include "CX/Hash/MultiHash.hpp"
#include "CX/Hash/SHA1Hash.hpp"
#include "CX/Hash/SHA224Hash.hpp"
#include "CX/Hash/SHA256Hash.hpp"
#include "CX/Hash/SHA384Hash.hpp"
#include "CX/Hash/SHA512Hash.hpp"
#include "CX/Hash/xxHash32.hpp"
#include "CX/Hash/xxHash64.hpp"
#include "CX/IO/BufferedInputStream.hpp"
#include "CX/IO/BufferedOutputStream.hpp"
#include "CX/IO/FileInputStream.hpp"
#include "CX/IO/FileOutputStream.hpp"
#include "CX/IO/FilteredInputStream.hpp"
#include "CX/IO/FilteredOutputStream.hpp"
#include "CX/IO/Helper.hpp"
#include "CX/IO/IFileSysEnumerator.hpp"
#include "CX/IO/IFileSysHelper.hpp"
#include "CX/IO/IFileSysHelper.hpp"
#include "CX/IO/IInputFilter.hpp"
#include "CX/IO/IInputFilter.hpp"
#include "CX/IO/IInputStream.hpp"
#include "CX/IO/IOutputFilter.hpp"
#include "CX/IO/IOutputStream.hpp"
#include "CX/IO/LocalFileSysEnumerator.hpp"
#include "CX/IO/LocalFileSysHelper.hpp"
#include "CX/IO/MemInputStream.hpp"
#include "CX/IO/MemOutputStream.hpp"
#include "CX/IO/MemoryMappedFile.hpp"
#include "CX/IO/Platform/Windows/FileInputStream.hpp"
#include "CX/IO/Platform/Windows/FileOutputStream.hpp"
#include "CX/IO/Platform/Windows/LocalFileSysEnumerator.hpp"
#include "CX/IO/Platform/Windows/LocalFileSysHelper.hpp"
#include "CX/IO/Platform/Windows/MemoryMappedFile.hpp"
#include "CX/Limits.hpp"
#include "CX/List.hpp"
#include "CX/Log/ConsoleOutput.hpp"
#include "CX/Log/DefaultFormatter.hpp"
#include "CX/Log/IFormatter.hpp"
#include "CX/Log/IOutput.hpp"
#include "CX/Log/Level.hpp"
#include "CX/Log/LogScope.hpp"
#include "CX/Log/Logger.hpp"
#include "CX/Log/OptimizedStreamOutput.hpp"
#include "CX/Log/Platform/Windows/ConsoleOutput.hpp"
#include "CX/Log/Platform/Windows/SystemOutput.hpp"
#include "CX/Log/SystemOutput.hpp"
#include "CX/Map.hpp"
#include "CX/Mem.hpp"
#include "CX/Network/HTTP/Client.hpp"
#include "CX/Network/URLParser.hpp"
#include "CX/Platform.hpp"
#include "CX/Print.hpp"
#include "CX/Queue.hpp"
#include "CX/STLAlloc.hpp"
#include "CX/Scope.hpp"
#include "CX/ScopePtr.hpp"
#include "CX/Set.hpp"
#include "CX/SimpleBuffers/BSONReader.hpp"
#include "CX/SimpleBuffers/BSONValue.hpp"
#include "CX/SimpleBuffers/BSONWriter.hpp"
#include "CX/SimpleBuffers/CPPGenerator.hpp"
#include "CX/SimpleBuffers/Custom.hpp"
#include "CX/SimpleBuffers/DataIniter.hpp"
#include "CX/SimpleBuffers/DataReader.hpp"
#include "CX/SimpleBuffers/DataWriter.hpp"
#include "CX/SimpleBuffers/Generic.hpp"
#include "CX/SimpleBuffers/Helper.hpp"
#include "CX/SimpleBuffers/IGenerator.hpp"
#include "CX/SimpleBuffers/IReader.hpp"
#include "CX/SimpleBuffers/ISimpleBuffer.hpp"
#include "CX/SimpleBuffers/IWriter.hpp"
#include "CX/SimpleBuffers/JSONReader.hpp"
#include "CX/SimpleBuffers/JSONWriter.hpp"
#include "CX/SimpleBuffers/Member.hpp"
#include "CX/SimpleBuffers/MemberType.hpp"
#include "CX/SimpleBuffers/Object.hpp"
#include "CX/SimpleBuffers/Parser.hpp"
#include "CX/SimpleBuffers/Version.hpp"
#include "CX/Slice.hpp"
#include "CX/SparseHashHelper.hpp"
#include "CX/SparseHashMap.hpp"
#include "CX/SparseHashSet.hpp"
#include "CX/SparseMultiHashSet.hpp"
#include "CX/Stack.hpp"
#include "CX/Status.hpp"
#include "CX/StatusCodes.hpp"
#include "CX/Str/Base64BinStr.hpp"
#include "CX/Str/HexBinStr.hpp"
#include "CX/Str/IBinStr.hpp"
#include "CX/Str/Platform/Windows/UTF8.hpp"
#include "CX/Str/StringHelper.hpp"
#include "CX/Str/UTF8.hpp"
#include "CX/Str/WildMat.hpp"
#include "CX/Str/Z85BinStr.hpp"
#include "CX/String.hpp"
#include "CX/Sys/Atomic.hpp"
#include "CX/Sys/BOM.hpp"
#include "CX/Sys/ByteOrder.hpp"
#include "CX/Sys/DynLib.hpp"
#include "CX/Sys/Event.hpp"
#include "CX/Sys/FastRWLock.hpp"
#include "CX/Sys/Lock.hpp"
#include "CX/Sys/Platform/Windows/Atomic.hpp"
#include "CX/Sys/Platform/Windows/DynLib.hpp"
#include "CX/Sys/Platform/Windows/Event.hpp"
#include "CX/Sys/Platform/Windows/FastRWLock.hpp"
#include "CX/Sys/Platform/Windows/Lock.hpp"
#include "CX/Sys/Platform/Windows/Process.hpp"
#include "CX/Sys/Platform/Windows/RWLock.hpp"
#include "CX/Sys/Platform/Windows/TaskExecutor.hpp"
#include "CX/Sys/Platform/Windows/TaskQueue.hpp"
#include "CX/Sys/Platform/Windows/Thread.hpp"
#include "CX/Sys/Process.hpp"
#include "CX/Sys/RWLock.hpp"
#include "CX/Sys/TaskExecutor.hpp"
#include "CX/Sys/TaskQueue.hpp"
#include "CX/Sys/Thread.hpp"
#include "CX/Types.hpp"
#include "CX/UOMap.hpp"
#include "CX/UOMultiMap.hpp"
#include "CX/UOMultiSet.hpp"
#include "CX/UOSet.hpp"
#include "CX/Util/Bitmap.hpp"
#include "CX/Util/CircularBuffer.hpp"
#include "CX/Util/Console.hpp"
#include "CX/Util/DynMember.hpp"
#include "CX/Util/DynStruct.hpp"
#include "CX/Util/MemPool.hpp"
#include "CX/Util/Platform/Windows/Console.hpp"
#include "CX/Util/Platform/Windows/Time.hpp"
#include "CX/Util/Platform/Windows/Timer.hpp"
#include "CX/Util/RCMemBuffer.hpp"
#include "CX/Util/RCMemBufferMgr.hpp"
#include "CX/Util/RndGen.hpp"
#include "CX/Util/Time.hpp"
#include "CX/Util/Timer.hpp"
#include "CX/Value.hpp"
#include "CX/Var.hpp"
#include "CX/Vector.hpp"
#include "CX/Version.hpp"
